#!/usr/bin/env python3
#
# BTZen - Bluetooth Smart sensor reading library.
#
# Copyright (C) 2015-2017 by Artur Wroblewski <wrobell@riseup.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
Script to test reading data from sensors in two different threads.

Expect no timeouts when reading sensor data.
"""

import argparse
import logging
import time
from concurrent.futures import ThreadPoolExecutor

import btzen

logging.basicConfig(level=logging.DEBUG)

parser = argparse.ArgumentParser()
parser.add_argument('device', help='MAC address of device')
args = parser.parse_args()

print('connecting to {}...'.format(args.device))
s1 = btzen.Pressure(args.device)
s2 = btzen.Temperature(args.device) 
s1.connect()
s2.connect()

executor = ThreadPoolExecutor(2)
for i in range(10):
    t1 = executor.submit(s1.read)
    t2 = executor.submit(s2.read)
    print(t1.result(), t2.result())

executor.shutdown()

s1.close()
s2.close()

# vim: sw=4:et:ai
